name: '522'
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.11,<3.13
  - pip
  - ipykernel
  - nb_conda_kernels
  - scipy
  - matplotlib>=3.2.2
  - scikit-learn
  - requests>=2.24.0
  - graphviz
  - python-graphviz
  - nltk
  - imbalanced-learn
  - pip:
      - altair-ally==0.1.1
      - seaborn==0.13.2
      - ucimlrepo==0.0.7
